version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: final_project_postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "255885"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d final_project_postgres_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: spring_app
    ports:
      - "8081:8081"
#    volumes:
#      - ./uploads:/app/uploads
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/final_project_postgres_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=255885
      - SPRING_MONGODB_URI=mongodb://mongo:27017/final_project_mongo_db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_healthy

volumes:
  postgres_data:
  mongo_data: