spring.application.name=FINAL_EXAM_ChervonenkoEkaterina
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://db:5432/final_project_postgres_db
spring.datasource.username=postgres
spring.datasource.password=255885
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# MongoDB
spring.mongodb.uri=mongodb://mongo:27017/final_project_mongo_db

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=katysik.chervonenko@gmail.com
spring.mail.password=didk pmem sxgd dlvl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.debug=true

springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always