spring.application.name=FINAL_EXAM_ChervonenkoEkaterina
server.port=8081

# --- PostgreSQL (????????????) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/final_db
spring.datasource.username=postgres
spring.datasource.password=255885
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- MongoDB (?????) ---
spring.data.mongodb.url=mongodb://localhost:27017/content_db

# --- JWT and Security ---
app.jwt.secret=v9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRgUkXp2s5v8y/B?E(G+KbPeShVmYq
app.jwt.expiration=86400000

# --- Gmail ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=katysik.chervonenko@gmail.com
spring.mail.password=didk pmem sxgd dlvl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.debug=true